version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viranava_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - backend/.env
    restart: always

  frontend:
    image: nginx:alpine
    container_name: viranava_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always
